### ISSUE TITLE
World crashes when trying to ask Guide for help in a non-terraria world

### ISSUE THREAD

**Issue by Xanderrock98** [TerrariaCraft/Issues#101]
**WARNING!**
You must fill out the following information in order to receive any help.
Leaving things "as-is" does not provide us with any useful information.
This warning may be deleted.

**Describe the bug**
When I ask the Guide for help in a non-terraria world, the world crashes and takes me to the multiplayer menu.

**To Reproduce**
1. Create a non-terraria world
2. Build house for the Guide
3. Interact with the Guide and click "Help"
4. World crashes

**Expected behavior**
The Guide gives you help

**Screenshots**
![image](https://user-images.githubusercontent.com/84468238/235322820-61e4490f-cbd7-4252-b129-846b8fc6be31.png)

**Mod Versions (please complete the following information):**
 - Minecraft Forge: 14.23.5.2860
 - HammerLib (HammerCore): 2.0.6.32
 - TerrariaCraft: 12.5.32
 - MusicLayer: 12.3.21
 - OpenCubicChunks: 1.12.2-0.0.1208.0-SNAP
 - Colored Lux: 12.6.30
 - Corsaire McCue: 12.4.8
 - Optifine Installed: no
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Intel(R) Core(TM) i7-10750H
 - GPU: Intel(R) UHD Graphics
 - RAM: not sure
 - Java: Java 8 Update 361 (64-bit)

**Additional context**
Add any other context about the problem here. For example, if your game crashes, attach a link to [Pastebin](https://pastebin.com) with a crash report pasted in there (full crash report, do not strip any part of it, it might be crucial for figuring the issue out!)

**Comment by Zeitheron** [comment]
Under any case you should never use TerrariaCraft things outside of TerrariaCraft-generated worlds, period.
They are designed to handle the fact that the world has extra data, that a normal world doesn't.
