### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by FletchyStrike** [TerrariaCraft/Issues#106]
cannot sign in into the game once opened ( when it asks for email and password )

**Comment by Zeitheron** [comment]
Please provide more details.

**Comment by FletchyStrike** [comment]
Well , when i open the Terraria craft game on pc , and it opens up a login window ( which you have to insert your mojang info with password ) well when i put my mojang account and password .. nothing happens and in the Codex Window it shows codes something like ( not found etc .. ) so im trying to understand how to be able to connect

**Comment by Zeitheron** [comment]
Mojang accounts no longer work after the account migration, use Microsoft accounts instead.

**Comment by FletchyStrike** [comment]
yes i connected with my microsoft account also and does nothing x) ..
