### ISSUE TITLE
[BUG] Official TerrariaCraft ModPack won't start with an included mod and won't load a world.

### ISSUE THREAD

**Issue by Radactivi** [TerrariaCraft/Issues#107]
**Describe the bug**
Modpack started with a mod that had issues (McCUE) and so i removed it, after launching again, and creating a world, it is stuck at 0% and nothing happens. Third time i launch it, the mod Hammer Core was also causing issues.

**To Reproduce**
(MacOS Ventura)
1. Install the pack and launch
2. Get error that McCUE has issues and remove it
3. Launch pack again and create world, which gets stuck at 0%
4. Relaunch the pack and Hammer Core has issues now. Also stuck on 0% when joining worlds.

**Expected behavior**
A straight-forward experience after installing the Official pack on CurseForge Launcher

**Screenshots**
1st crash: 
![image](https://github.com/TerrariaCraft/Issues/assets/126182931/f1f211d7-8e08-4013-b23a-a9c01a034be3)
Loading world: 
![image](https://github.com/TerrariaCraft/Issues/assets/126182931/38dcd611-c4e3-4fbf-8ec3-a026d1a54f39)
2nd crash: 
![image](https://github.com/TerrariaCraft/Issues/assets/126182931/44e91f9a-bd5d-401f-be4f-5bb88ff31f24)

**Mod Versions (please complete the following information):**
 All the mods in the latest pack (In Fri. 4. Aug 2023), no extra mods.
 
 **Hardware & Software info (Might be important in some cases)**
(MacBook Pro 2019) 
- CPU: 2.6 GHz 6-Core Intel Core i7
 - GPU: AMD Radeon Pro 5300M 4 GB
             Intel UHD Graphics 630 1536 MB
 - RAM: 16 GB 2667 MHz DDR4
 - Java: Included Java, Latest Java 8, Java 17

**Additional context**
1st crash report: https://pastebin.com/RKKBrBLV
2nd crash report: https://pastebin.com/pr0hvaxR
3rd crash report: https://pastebin.com/YPM97RCr

**Comment by Zeitheron** [comment]
java.lang.OutOfMemoryError: Requested array size exceeds VM limit


The solution is, quite simply, allocating 4-6 GBs of memory.
