### ISSUE TITLE
Crash on a fresh server

### ISSUE THREAD

**Issue by cancerdancer1337** [TerrariaCraft/Issues#11]
Brand new server made just to chill with a few mates of mine using just this mod and it's four dependencies. Crashes pretty quick, server.properties are still blank
https://pastebin.com/4Ehxm61L

**Comment by Zeitheron** [comment]
Thanks, the issue has been fixed in dev.

**Comment by OrHy3** [comment]
> 
> 
> Thanks, the issue has been fixed in dev.

Sorry if I ask such a dumb question, but where can I get instructions or eventually files to fix the issue? (I got the same identical issue)

**Comment by cancerdancer1337** [comment]
Gotta wait for a new release it seems.

**Comment by OrHy3** [comment]
OK, thanks for the answer

**Comment by Zeitheron** [comment]
Fixed, finally.
