### ISSUE TITLE
It says i dont have my patreon connected

### ISSUE THREAD

**Issue by monkeyseemonkeydo101** [TerrariaCraft/Issues#110]
I bought the 10$ subscription and i connected my discord account but the bot still says i have not subscribed on patreon

**Comment by Zeitheron** [comment]
This is not a mod issue, but Patreon is a bit slow.
Give it some time before and make sure that our bot can message you:
![image](https://github.com/TerrariaCraft/Issues/assets/38943617/c79458f5-8aee-4493-ab4d-82bf0fa69ce0)

**Comment by monkeyseemonkeydo101** [comment]
Thank you sir. I will be patient.
