### ISSUE TITLE
[BUG] Texture pack issue

### ISSUE THREAD

**Issue by AlexPhoton** [TerrariaCraft/Issues#113]
**Describe the bug**
I passed this point downloaded the texture pack suggested and have it up and running, but food eg. lemon, apple also slimes that drop potion bottles, potion bottles come up with pink and black boxes. Is there a newer Texture pack, i should have downloaded?

**To Reproduce**

**Expected behavior**
I'm pretty sure i have messed something up just need to be guided into the right direction

**Screenshots**
![Terraria Craft 12 5 32 2023-11-06 10_lesser healing](https://github.com/TerrariaCraft/Issues/assets/149988421/e4b9349c-6723-4643-b38d-1e774a9eeb51)

**Mod Versions (please complete the following information):**
 Upto date from forge Terraricraft unofficial 1.01 zip
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: i7 -13700F
 - GPU:  NVIDIA GeForce RTX 4070 
 - RAM: 32gb
 - Java: Java 8 Update 231 (64-bit)

**Additional context**
No crashes plays well

**Comment by Zeitheron** [comment]
`Upto date from forge Terraricraft unofficial 1.01 zip`
