### ISSUE TITLE
World Not Loading

### ISSUE THREAD

**Issue by GyattOhioRizzler** [TerrariaCraft/Issues#116]
**Describe the bug**
The bug is when I start or load a world, it says "World Loading" and then it shows "0%" and gets stuck there.
**To Reproduce**
1. Go to curseforge or the terrariacraft website and download the Official TerrariaCraft Modpack
2. Play the modpack
3. press singleplayer
4. load or create a world
5. The world gets stuck at "0%"

**Expected behavior**
I expected for me to create a world, and then the world to load so I could play the mod.

 -Minecraft- 1.12.2
- Forge - 14.23.5.2860
Betterfps - 1.4.8
Colored Lux - 1.12.2-12.6.30
CubicChunks - 1.12.2-0.0.1208.0-snapshot-all
FoamFix-0.10.14-1.12.2
HammerLib-1.12.2-2.0.6.32
MusicLayer - 1.12.2-12.3.21
TerrariaCraft - 1.12.2-12.5.32
RecipeViewer - 1.12.2-5.2.7
VanillaFix-1.0.10-150
 - Optifine Installed: [NO]

**Comment by Zeitheron** [comment]
Check and see if it still happens with 12.6 pre-release, available through our [launcher](https://terrariacraft.com/download#launcher)

**Comment by GyattOhioRizzler** [comment]
> launcher

The launcher keeps crashing everytime I try to open it, I'm on mac
I already signed in

**Comment by Zeitheron** [comment]
Wasn't ever able to replicate.
