### ISSUE TITLE
No Screen/Crash on launch after installing CubicChunks mod

### ISSUE THREAD

**Issue by cbost4j98** [TerrariaCraft/Issues#12]
![craft](https://user-images.githubusercontent.com/69099194/89115292-b8bda880-d454-11ea-9817-013be688035f.PNG)

After doing all the steps and getting all the mods required I still happen to run into this issue. Whenever I try loading into the game with all the mods including CubicChunks and I always have to go in my Task Manager to End Java. Is there something that I am missing? Because I've tried every Cubic Chunk mod and none of them worked and usually add more problems with the others that aren't recommended. The image above is what I get when i take the CubicChunks mod out of the mod folder so if I'm missing something important please let me know because I've been dying to play this mod.

Thank you :) 
cbost4j98

**Comment by Zeitheron** [comment]
just be patient

**Comment by cbost4j98** [comment]
be patient about what? I downloaded every mod i need... and it crashes idk what to do but obviously you didnt read that because i asked you a question if there was something i forgot to download and that might be why but I really needed help and all you can say is "just be patient" like what do you mean by that? am i waiting for something? like please help me install this mod correctly

**Comment by cbost4j98** [comment]
cause you closed it with no solution to the problem. I have been patient but i need to know how to install this correctly

**Comment by cbost4j98** [comment]
I've been wanting to play Terraria Craft but the mod creator cant even help me

**Comment by Zeitheron** [comment]
You need OpenCubicChunks. it is listed as a required dependency.

**Comment by cbost4j98** [comment]
![mc](https://user-images.githubusercontent.com/69099194/89120122-b1f95a80-d481-11ea-893d-f2d7b32f53eb.PNG)

**Comment by cbost4j98** [comment]
Is it a different file?

**Comment by Zeitheron** [comment]
the installation seems correct.
You mentioned long loading screen. That is where you have to be patient. CC takes a bit to try and find the spawn  location, which is a horrible thing in itself, but I can do nothing here. Just wait while it loads.

**Comment by cbost4j98** [comment]
Even when the forge loading screen won't pop up?

**Comment by cbost4j98** [comment]
The game wont load to even get to create a world

**Comment by Zeitheron** [comment]
then send the crash report, I can't work with just words at this point.

**Comment by Zeitheron** [comment]
Also update TerrariaCraft to latest 12.2.16

**Comment by cbost4j98** [comment]
yeah im getting the crash report right now and I think it is but i'll double check

**Comment by cbost4j98** [comment]
[latest.log](https://github.com/TerrariaCraft/Issues/files/5011933/latest.log)

**Comment by cbost4j98** [comment]
I hope thats the right one lol

**Comment by Zeitheron** [comment]
Oh. It is Optifine related crash. just  remove OF, it conflicts with cubic chunks
Well, your version of OF conflicts with CC

**Comment by cbost4j98** [comment]
Oh damn so I need a version of OF thats supported

**Comment by Zeitheron** [comment]
You have literally the oldest OF available, try upgrade to F5
![image](https://user-images.githubusercontent.com/38943617/89120485-53eb6800-d4bf-11ea-9e3a-ee0f983ab475.png)

**Comment by cbost4j98** [comment]
Well thank you so much it worked sorry i came off a little irritated Zeitheron you're awesome and keep up the good work. Didn't realize it was going to be such an easy fix I swear XDD but anyways stay safe in these uncertain times fam.

cbost4j98

**Comment by Zeitheron** [comment]
Thanks for sticking along the mod's development, have fun!

**Comment by cbost4j98** [comment]
[crash-2020-08-02_06.02.49-server.txt](https://github.com/TerrariaCraft/Issues/files/5011939/crash-2020-08-02_06.02.49-server.txt)

**Comment by cbost4j98** [comment]
spoke too soon lmao

**Comment by Zeitheron** [comment]
That crash is quite odd
Try creating a different  world?

**Comment by cbost4j98** [comment]
Yeah that fixed it, I think cause it had a shitty terraria mod in the world data that i tried before I saw this one on youtube.

**Comment by Zeitheron** [comment]
You have to create a new world with type "Terraria World"
otherwise the mod does not accept other worlds.

**Comment by cbost4j98** [comment]
Yeah my bad lol thank you again :)

**Comment by cbost4j98** [comment]
[crash-2020-08-03_00.46.56-server.txt](https://github.com/TerrariaCraft/Issues/files/5013949/crash-2020-08-03_00.46.56-server.txt)

**Comment by cbost4j98** [comment]
[crash-2020-08-03_01.05.18-server.txt](https://github.com/TerrariaCraft/Issues/files/5014000/crash-2020-08-03_01.05.18-server.txt)

**Comment by cbost4j98** [comment]
if you're still there what is this crash report?
