### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Guts606** [TerrariaCraft/Issues#121]
when I try to log into my account through Microsoft, at first it just logs out, and when I try again I get a white screen
P.S I downloaded the Windows Installer version (x86-64)

![image](https://github.com/TerrariaCraft/Issues/assets/169879538/4735a8f3-bb3e-4d24-b974-23166685b0b5)
![image](https://github.com/TerrariaCraft/Issues/assets/169879538/70194d9a-9aeb-4c70-ad7c-c58d80cdf518)

**Comment by yorel0950** [comment]
I just want to add that I'm having the same issue. Tried both methods of logging in and I'm getting no change to the login screen.
<img width="324" alt="Screenshot 2024-06-04 223148" src="https://github.com/TerrariaCraft/Issues/assets/171770864/954c5706-4efc-4fd2-b4cc-b5c6072e456e">

**Comment by Zeitheron** [comment]
I'll roll an update that will log things to a file. Then I'm going to get back ans request a log file for review.
