### ISSUE TITLE
[BUG] Crash upon trying to start (Terrariacraft Mod version)

### ISSUE THREAD

**Issue by yorel0950** [TerrariaCraft/Issues#122]
**Describe the bug**
I downloaded the mod through curseforge, launched it through curseforge and pressed play. Shortly after the Terrariacraft window opened and it was loading the mods, I got a crash report and have added it below.

**To Reproduce**
Steps to reproduce the behavior (unsure if it is reproduceable on other systems)
1. Download via curseforge
2. Open minecraft launcher via curseforge
3. Download and attempt to launch the game
4. See bug

**Expected behavior**
I expected the game to simply launch.

**Screenshot**
<img width="410" alt="Screenshot 2024-06-04 230158" src="https://github.com/TerrariaCraft/Issues/assets/171770864/b8e38dc1-7393-4d15-9f76-57e1e6820c53">

**Mod Versions:**
 - Minecraft Forge: (Sorry, I'm not sure what this is asking for
 - HammerLib (HammerCore) 1.12.2-12.2.50
 - TerrariaCraft 1.12.2-12.6.2
 - MusicLayer 1.12.2-12.2.22
 - OpenCubicChunks 1.12.2-0.0.1271.0-SNAPSHOT-all
 
 **Hardware & Software info**
 - CPU: 13th gen Intel(R) Core(TM) i9-13900H
 - GPU: NVIDIA GeForce RTX 4070 Laptop
 - RAM: 32 GBs (unsure of speed)
 - Java: Java 8 update 411

**Additional context**
Pastebin link to the crash file here: (https://pastebin.com/jJsspe3T)

**Comment by Zeitheron** [comment]
Update to latest java 1.8 (java 8). Alternatively , considering using our launcher.
