### ISSUE TITLE
[BUG] King Slime crash

### ISSUE THREAD

**Issue by Snowdragon100** [TerrariaCraft/Issues#123]
King Slime crashed the game once summoned in hell with 2 render distance

I order to recreate this, use modrinth for getting the mod and the 2 addons, create a large world in classic creative cheats, go to hell, and summon king slime with slime crown.

crash report (pastebin.com edited the crash report and made it smaller):
https://docs.google.com/document/d/1U8vs8cCGSG5jB-B10OXF9cZgFe92gDvHqu58DK9r8mA/edit?usp=sharing

**Comment by Zeitheron** [comment]
Never provide crash reports in google docs. That is literally unreadable and also it's just a lower part of the crash report.
