### ISSUE TITLE
Flying enemies spawning excessively

### ISSUE THREAD

**Issue by RikoComet** [TerrariaCraft/Issues#126]
I've noticed while playing that at night time or in evil biomes I'm often swarmed by lots of flying enemies, and I'm not certain if this is intended behavior. It's not uncommon for 1 demon eye to turn into 5 or 6 in the span of a few seconds. They likely don't actually spawn any more frequently than ground mobs do but because they're a little harder to hit in 3D, it's difficult to kill them fast enough to prevent a dangerous swarm from accruing, especially on harder difficulties. I do admit i have been playing on expert difficulty which could be increasing their spawn rates, but i noticed the issue in the previous version of the mod as well.

**Comment by Zeitheron** [comment]
All enemy spawns have been nerfed on idev builds to be more on-par with Terraria.

I'll consider this issue fixed unless it will be raised in 12.7 versions of the mod.
