### ISSUE TITLE
[BUG] Horseshoe not working

### ISSUE THREAD

**Issue by Tucky143** [TerrariaCraft/Issues#128]
**Describe the bug**
You still take fall damage with the horseshoe equipped

**To Reproduce**
1. Equip 'horseshoe.'
2. Fall

**Expected behavior**
you shouldn't take fall damage

**Mod Versions (please complete the following information):**
 - Minecraft Forge: [e.g. 14.23.5.2847]
 - Terraria Craft [latest]

**Comment by Zeitheron** [comment]
Fixed in early access already.
