### ISSUE TITLE
[BUG] Terraria Craft Crashes when player is NOT in Biome Terraria

### ISSUE THREAD

**Issue by Solxanich** [TerrariaCraft/Issues#13]
**Describe the bug**

**To Reproduce**
1. Place '...'
3. See error

**Expected behavior**

**Screenshots**

**Mod Versions (please complete the following information):**
 - Minecraft Forge: [e.g. 14.23.5.2847]
 - HammerLib (HammerCore) [e.g. 2.0.6.19]
 - TerrariaCraft [e.g. 12.2.13]
 - MusicLayer [e.g. 12.2.20]
 - OpenCubicChunks [e.g. 0.0.1055.0]
 - (if installed) ColoredLux [e.g. 12.3.17]
 - Optifine Installed: [yes/no] (Only required for visual debugging)
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: [e.g. AMD Ryzen 9 3900x] (lookup in task manager)
 - GPU: [e.g. NVIDIA GeForce RTX 2070 SUPER] (lookup in task manager)
 - RAM: [e.g. 64 GBs @ 3000 MHz] (lookup in task manager)
 - Java: [e.g. Java 8 Update 231 (64-bit)] (lookup in apps)

**Additional context**
Add any other context about the problem here. For example, if your game crashes, attach a link to [Pastebin](pastebin.com) with a crash report pasted in there (full crash report, do not strip any part of it, it might be crucial for figuring the issue out!)

**Comment by Zeitheron** [comment]
excuse me what the fuck
