### ISSUE TITLE
Chest and Merchant crash and kick me out ot the main menu -

### ISSUE THREAD

**Issue by rodriog** [TerrariaCraft/Issues#131]
**Describe the bug**
Every time I try to buy something from the merchant or open a chest, the game freezes and crashes, showing me an error. I have tried restarting, using different launcher options, and also checking the garbage collector is on ZGC and the game on latest version but nothing has worked.

**To Reproduce**
1. open chest  or talk to merchant
2. Try to buy or move something
3. game slow down them freeze and finally crash

**Expected behavior**
Being able to buy or save items on chests

**Screenshots**
![imagen_2024-08-31_214702845](https://github.com/user-attachments/assets/fc4c9f23-cd5a-409d-8a7a-46e58bf5a347)

**Mod Versions**
 - Minecraft Forge: [e.g. 14.23.5.2847]
 - HammerLib (HammerCore) 12.2.56
 - TerrariaCraft 12.6.2
 - MusicLayer 12.2.22
 - OpenCubicChunks 1.12.2-0.0.1271.0-SNAP
 - ColoredLux 12.6.33
 - Optifine Installed: no
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Intel Core i7 4790k
 - GPU: Nvidia GeForce GTX 1060 5GB
 - RAM: 20gb 3994.8 MHZ
 - Java: 64 bit Java 8

**Comment by Zeitheron** [comment]
Can't validate on the early access.

**Comment by rodriog** [comment]
What do you mean?
