### ISSUE TITLE
[BUG] Inventory menu getting unbelievably lag sometimes and other issues i had with the mod so far

### ISSUE THREAD

**Issue by MistereMoth** [TerrariaCraft/Issues#134]
The project has all the right to be flawed as it's a passionate non-profit project that does the impossible of turning minecraft into 3d terraria, and so far it's been doing a phenomenal job, but it's still important to report the flaws with the game that either make the gameplay experience more difficult and frustrating. 

- ~~Whenever i open the inventory, the game gets unbelievably laggy. I'm playing on the official terrariacraft on my computer with about 16GB of RAM. It's quite inconsistent when it lags to keep track of, but seems to be in conjunction with other things that cause heavy RAM consume such as having a browser opening or being near a light source.~~

-Lack of some main features from the base terraria game, making the gameplay unecessarily slower and frustrating, i understand that these features might still get added, but considering how integral they are to the base game and make the experience better, it's weird how they're yet to be implemented:
- >Accessing the full crafting menu so we won't have to scroll through all recipes, which gets worse when we have a lot of available crafting recipes.
- >Autofire.
- >Map, this one is understandably harder to implement due to being 3d rather than 2d, but still i hope we get a map in someway, even if it'll be closer to minecraft's map, in case there already is let me known
- >We can't use ammo slot items for crafting, isn't that bad but made me scratch my head on why i couldn't craft torches and mana crystals for way too long.

-Perhaps the hitbox of swing melee weapons such as swords should be wider horizontally. The hitbox seems to be the same as in terraria, with it going in a vertical arc from the player's head to front, but in 3d it seems to barely have any depth extension to the hitbox, making it really hard to protect myself from THE THOUSANDS OF DEMON EYES THAT SPAWN EVERYTIME AT NIGHT.

-As the previous issue mentioned, the enemy spawn rate is way too high! Probably as the game seemingly ports everything almost exactly how they are from the base terraria game, and try to adapt them to 3d. The enemy spawn rate is a clear example of something that can't just remain completely faithful to the original game. If the spawn rate is the same while the game has a whole 3rd dimension, this means that the spawnrate would essentially get SQUARED (multiplied by itself). This isn't much of a problem as it's much easier to dodge most enemies with a whole new dimension, except for enemies like demon eyes, which can be very hard to dodge in early game without many movement options, and it just gets even worse with a swarm of them (which you'll very likely get through the whole night), and as I already stated, melee weapons aren't so effective to deal with them.

-On the other side of the spectrum when i went to the caves no enemies spawned at all (i'm playing on master btw).

Those are the issues i got with the mod so far, as I play more I might find more issues that really sour my experience to report (hopefully I won't).
Best wishes for all of Ukraine

edit: i really gotta learn to use this site

**Comment by Zeitheron** [comment]
Inventory lag was fixed a while ago.

Crafting grid was already added.

Autofire works on some weapons, which have autofire in Terraria itself.

Minimap...for now use VoxelMap.

Spawns have been severely reduced to feel more terraria-like, even in 3D space.

Cave enemies aren't in the latest public release, however if you are tracking the spoilers we post on Discord, YouTube, Twitter, Telegram & Bluesky, you can see that there are quite a lot of new enemies getting added into the next major release.

Things that I did not address here are yet to be tackled.

**Comment by MistereMoth** [comment]
very weird... maybe terrariacraft from the modpack isn't on the latest version, i'm gonna check out

also something else i noticed is that for some reason lead axe was slower than the copper one (first took aprox 18 axe swings while later 12) but i'm gonna check again once and if i can update the modpack

**Comment by Zeitheron** [comment]
The latest public version hasn't been updated for a while, that's not the problem. Things are coming to next public build!

**Comment by Takogawa21** [comment]
the Inventory lag / chest Inventory lag is still there for me to so cant be patched

**Comment by Zeitheron** [comment]
Please check release dates before reporting the issue hasn't been fixed.

**Comment by Kurhuzo** [comment]
> Please check release dates before reporting the issue hasn't been fixed.

Terrariacraft 12.6.2
It was running alright for me but now when i open my inventory the game LAGS completely and then i get dissconnected. How to I fix this??? I love the mod and want to continue it.


Picture is the f3 info when i have the inventory open (you can see the ridiculous spike in lag) and the. It crashes if i dont close the inventory.

![IMG_0682](https://github.com/user-attachments/assets/fb915315-5951-438e-9e52-1ebdc8dbb956)


Then i get the message: Internal Exception: java.nio.channels.ClosedChannelException
