### ISSUE TITLE
[BUG] Crazy frame drops to 0fps when breaking blocks.

### ISSUE THREAD

**Issue by GamerLoganDean** [TerrariaCraft/Issues#135]
Whenever I break and place blocks, I get frame drops to 0fps. I have pretty good specs so I am not sure why it is doing this. I am running the LATEST version of the modpack. I will send a screenshot of my specs. Java Version: 1.8.0_392
![Screenshot 2024-09-28 153422](https://github.com/user-attachments/assets/9ed40973-ebad-4c04-b675-ef8d514f69b4)

**Comment by Zeitheron** [comment]
CubicChunks causing this lag because of light updates. Check if your chunk has a lot of cavities, that seems to degrade performance a lot.

Will have to close this as it's CC issue.
