### ISSUE TITLE
Bucket Duplication glitch

### ISSUE THREAD

**Issue by VRMira** [TerrariaCraft/Issues#136]
while playing with my wife this mod(awsome job btw we love it so far keep it up) ive descuverd a bug. in the actual game when you spam collect and place water with a bucket it infinatly placec it same with lava. i tryd it aswell in the mod too and it did kinde work exapt it didnt dublicated the water it dublicated the bucket of water as a hole creating a way to get infinite buckets.

**Comment by Zeitheron** [comment]
This was already reported and fixed.
