### ISSUE TITLE
[BUG] GL crash after loading world.

### ISSUE THREAD

**Issue by MaddTheSane** [TerrariaCraft/Issues#137]
**Describe the bug**

**To Reproduce**
1. Click on Single Player
2. Click on a world or create a new world.
3. world loading happens.
4. progress is stuck on %0 and does nothing.

**Expected behavior**
After world loading happens, I'm brought into the world of TerrariaCraft.

**Screenshots**

**Mod Versions (please complete the following information):**
 - Minecraft Forge: 14.23.5.2860
 - HammerLib (HammerCore) 12.2.50
 - TerrariaCraft 12.6.2
 - MusicLayer 12.2.22
 - OpenCubicChunks 0.0.1208.0
 - (if installed) ColoredLux 12.6.33
 - Optifine Installed: no (Only required for visual debugging)
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Apple M3 8 Core
 - GPU: Apple M3 10 Core
 - RAM: 24 GB LPDDR5
 - Java: [e.g. Java 10.0.16.1 (64-bit)]

**Additional context**

It looks like there's a problem with Colored Lux and macOS/M-series GPUs:

```
[00:22:02] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[00:22:02] [Client thread/ERROR] [minecraft/Minecraft]: @ Post render
[00:22:02] [Client thread/ERROR] [minecraft/Minecraft]: 1280: Invalid enum
```

This was launched and set up by Prism Launcher as a previous app that I tried for another server didn't work with Apple Silicon.

**Comment by Zeitheron** [comment]
Probably just apple things, I'm afraid.
I can not offer a fix for this, sorry.

**Comment by MaddTheSane** [comment]
Good news: disabling ColoredLux allows me to get into the game (and I realized that the server end was still going. So many tombstones…

Of course, now I'm getting shader compile errors for dyes.
