### ISSUE TITLE
[BUG/CRASH] mod refuses to open on any modloader and tells me about nashorn?

### ISSUE THREAD

**Issue by JAGamer001** [TerrariaCraft/Issues#138]
**Description**
on multiple different launchers, including modrinth, curseforge, and even polymc, TerrariaCraft loads for a few seconds, crashes, and in the crash logs, it reads:
PLEASE DO NOT REPORT THIS ISSUE! IT IS AN INTENTIONAL CRASH.
YOUR JAVA RUNTIME IS MISSING A CRITICAL COMPONENT FOR HammerAnimations: Nashorn.
CONSIDER INSTALLING NASHORN INTO YOUR MODS FOLDER, OR USING JDK INSTEAD OF JRE.
i switched from using java 17 to using java 8, which is meant for minecraft 1.12.2, and as far as i know, nashorn is a code library that was introduced in java 8 and is already included. i have switched to using a jdk version even with java 8, and it still gives me the same crash, and due to this, i am unable to play TerrariaCraft.

**To Reproduce**
1. download TerrariaCraft + its dependencies
2. boot up the game
3. crash (idk this is only happening to me probably)

**Expected behavior:**
i expected it to not work when using java 17, since nashorn was retired in java 17, and expected java 8 to work with the mod just fine

**Screenshots:**
i don't really have any screenshots, but you can find the modrinth crash logs here:
https://mclo.gs/WL3WFDx

**Mod Versions:**
 - Minecraft Forge: 14.23.5.2860
 - HammerLib (HammerCore) 12.2.56
 - TerrariaCraft 12.6.2
 - MusicLayer 12.2.22
 - OpenCubicChunks 1.12.2-0.0.1208.0
 - ColoredLux 12.6.33
 - Optifine Installed: no
 
 **Hardware & Software info:**
 - CPU: Intel Core i5-9400F
 - GPU: NVIDIA GeForce GTX 1650 SUPER
 - RAM: 16 GB
 - Java: Java 8 Update 412 (64-bit)

**Additional context**
https://mclo.gs/WL3WFDx
crash reports ^^

**Comment by Zeitheron** [comment]
Use TerrariaCraft launcher. It uses Java 21 to give extra performance, as well as uses updated and improved OpenJDK Nashorn engine.
