### ISSUE TITLE
[BUG] Monsters not spawning underground

### ISSUE THREAD

**Issue by MaddTheSane** [TerrariaCraft/Issues#139]
**Describe the bug**
Monsters aren't spawning underground.

**To Reproduce**
1. Dig until you find a cave.
2. Explore.
3. No monsters spawn.

**Expected behavior**
Hostile monsters spawn.

**Mod Versions (please complete the following information):**
 - Minecraft Forge: 14.23.5.2860
 - HammerLib (HammerCore) 12.2.50
 - TerrariaCraft 12.6.2
 - MusicLayer 12.2.22
 - OpenCubicChunks 0.0.1208.0
 - Optifine Installed: no (Only required for visual debugging)
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Apple M3 8 Core
 - GPU: Apple M3 10 Core
 - RAM: 24 GB LPDDR5
 - Java: 10.0.16.1 (64-bit)

**Additional context**
This has been observed in both the purity and the jungle.

**Comment by alessosussy** [comment]
i also have this problem on apple M3. this happens everywhere underground, once i go underground there is nothing :(

**Comment by Zeitheron** [comment]
This is because you are using old 12.6 builds.

**Comment by MaddTheSane** [comment]
I downloaded it from CurseForge. Is there a more up-to-date version?

**Comment by Zeitheron** [comment]
Use our launcher. It unlocks 12.7 pre-releases.
