### ISSUE TITLE
[BUG] Terraria Craft crashes when Player in not in Biome Terraria

### ISSUE THREAD

**Issue by Solxanich** [TerrariaCraft/Issues#14]
**Describe the bug**
As described in title. The server is crashing due to ticking entity. This mod is not usable in a modpack as is. First few lines:
       at tk.zeitheron.terraria.world.api.WorldgenHelper.getBiome(WorldgenHelper.java:34)
	at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:201)
	at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:79)
	at tk.zeitheron.terraria.common.data.player.PlayerDataTC.update_end(PlayerDataTC.java:301)

**To Reproduce**
1. Select world generator Default
2. Generate World
3. Server crashes

**Expected behavior**
The instance does not induce a crash when player not in Biome Terraria. This is not helpful for use in modpacks where multiple dimensions may be used to offer multiples sets of content via mods such as Just Enough Dimensions. Perhaps applying a check to the entity dimension id to determine if the world provider of that dim ID is valid for Terraria Craft's associated code?

**Mod Versions (please complete the following information):**
See crash report as needed. All up to date.
 
 **Hardware & Software info (Might be important in some cases)**
See crash report as needed. All up to date.

**Additional context**
Crash Report -> https://pastebin.com/Q3GTyZUd

**Comment by Zeitheron** [comment]
Do not generate non-terraria world type with this mod.

**Comment by Zeitheron** [comment]
For this: `This mod is not usable in a modpack as is.`
Do  NOT insert the mod into a pack, it is intended to be played as a standalone mod, not a part of a pack.

**Comment by Solxanich** [comment]
Thank you for the clarification and prompt response. 
I had to intended to use this mod via just enough dimensions and gamestaging to place it in it's own fully dedicated dimension to give more experience options to my players.
However, if the stance is that this is a standalone mod only, I would recommend you update your Curseforge page accordingly to state that 'this is a standalone mod' instead of stating that you can use it a modpack to avoid confusion in the future.

**Comment by Zeitheron** [comment]
okay, thanks for the suggestion.
