### ISSUE TITLE
[BUG] Low frames while crafting

### ISSUE THREAD

**Issue by CherrySeinfeld** [TerrariaCraft/Issues#141]
While im crafting anything within the game my computer goes from 120fps to 1fps.

When ever i stand above a crafting table or a forge, i go to craft items in the inventory and i loose all my frames making crafting almost impossible.

 - TerrariaCraft Curse Launcher  12.6.7

 - CPU: amd 9590
 - GPU: Nvidia Geforce GTX 1070
 - RAM: 16gb Corsair Vengance
 - Java 8 Update 421 (64-bit)

**Comment by Zeitheron** [comment]
Don't report on non-existing versions of the mod. Use TC Launcher to get the pre-release before reporting anything, thanks.
