### ISSUE TITLE
Unknown Control Menu Crash on exit

### ISSUE THREAD

**Issue by cbost4j98** [TerrariaCraft/Issues#15]
[crash-2020-08-04_08.12.21-client.txt](https://github.com/TerrariaCraft/Issues/files/5022001/crash-2020-08-04_08.12.21-client.txt)
 
I sent the crash report instead of explaining this time
get back to me asap 

cbost4j98

**Comment by Zeitheron** [comment]
Please provide steps to  reproduce this issue.

**Comment by cbost4j98** [comment]
I enter the controls option in optifine latest version for build and whenever i back out thats the crash report plz help thank you

**Comment by cbost4j98** [comment]
btw ps are there beds?

**Comment by cbost4j98** [comment]
Like what exactly do i need to tell you? cuz i guess its possibly normal

**Comment by cbost4j98** [comment]
that was the crash report like ill make one

**Comment by Zeitheron** [comment]
ok tried to fix.
