### ISSUE TITLE
Not being able to make a Bed to set a spawn point

### ISSUE THREAD

**Issue by cbost4j98** [TerrariaCraft/Issues#16]
Hey you guys I hope you're having a good one but I was leaving this issue because I have all the materials but I still cant make a bed. Can you even make a bed/spawn in Terraria craft? You added everything else important but not the the most important which is a bed so after you die you wont just spawn randomly somewhere. I don't know if the mod development team is working on it or not but it is quite irritating that there are no beds in one of the biggest mods in Minecraft. Get back to me as soon as you can.

Thank You,
cbost4j98

**Comment by Zeitheron** [comment]
Beds are not yet implemented. Please check stuff in-game first, before reporting.

**Comment by cbost4j98** [comment]
ummmm but i have checked in game... But you have a loom, sawmill, wood and silk and i just reported because I cant craft it but I should've figure because it wasn't in the creative menu. Thank you I wish you guys luck on making this the perfect 3D Terraria experience. Sorry for the misunderstanding and Inconvenience have an amazing day :))

Sincerely,
Cbost4j98
