### ISSUE TITLE
[Suggestion] Hold Alt for cursor

### ISSUE THREAD

**Issue by oliverrook** [TerrariaCraft/Issues#24]
As of right now, there isn't an easy way to quickly view buffs/debuffs. What could work, as well as giving the ability to click on things without opening the inventory, is pressing and/or holding the Alt-key to bring up the cursor. Not that big of a suggestion, but I think it could help in situations in which time matters.

Also I didn't know how/if I could change the label, which is why it says bug. Sorry about that.

**Comment by Zeitheron** [comment]
Really not sure how to implement that but it might be a good idea.

**Comment by Zeitheron** [comment]
Since the buffs are now rendered inside inventory, I'll consider this complete.
