### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dinokio** [TerrariaCraft/Issues#25]
I have this error everytime i start Terraria Craft. I have all recommended mods expect corsair. I also have Optifine.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.3.21.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1161.0-SNAPSHOT-all.jar)
  HCASM (HammerLib-1.12.2-2.0.6.26.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 1/15/21 8:00 PM
Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_175068_a(IFJ)V @1727: invokestatic
  Reason:
    Type 'net/minecraft/client/renderer/culling/ClippingHelper' (current frame, stack[2]) is not assignable to 'net/minecraft/entity/Entity'
  Current Frame:
    bci: @1727
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', integer, float, long, long_2nd, integer, 'net/minecraft/client/renderer/RenderGlobal', 'net/minecraft/client/particle/ParticleManager', integer, 'net/minecraft/client/renderer/culling/ClippingHelper', 'net/minecraft/client/renderer/culling/Frustum', 'net/minecraft/entity/Entity', double, double_2nd, double, double_2nd, double, double_2nd }
    stack: { integer, float, 'net/minecraft/client/renderer/culling/ClippingHelper', 'net/minecraft/client/renderer/EntityRenderer' }
  Bytecode:
    0x0000000: b804 4136 0515 0599 0009 1b24 21b8 06b9
    0x0000010: 2ab4 00e5 b402 1a3a 062a b400 e5b4 06bd
    0x0000020: 3a07 2ab7 06bf 3608 b806 c22a b400 e5b4
    0x0000030: 0227 1306 c4b6 05a6 1505 9900 1903 032a
    0x0000040: b400 e5b4 0169 2ab4 00e5 b401 6cb8 06c7
    0x0000050: a700 1603 032a b400 e5b4 0169 2ab4 00e5
    0x0000060: b401 6cb8 05c5 2a24 b706 ca11 4100 b805
    0x0000070: d915 0599 0006 b806 cd2a b400 e5b4 0227
    0x0000080: 1306 cfb6 05a6 2a24 1bb6 06d1 1505 9900
    0x0000090: 0724 b806 d4b2 06d7 b601 5399 0034 b206
    0x00000a0: d705 bd00 0559 032a b400 e5b6 0184 5359
    0x00000b0: 042a b400 e5b4 01a1 b403 b005 a000 0704
    0x00000c0: a700 0403 b806 dc53 b801 5757 a700 202a
    0x00000d0: b400 e5b4 01c2 2ab4 00e5 b401 a1b4 03b0
    0x00000e0: 05a0 0007 04a7 0004 03b8 06e0 2ab4 00e5
    0x00000f0: b402 2713 06e2 b605 a6b8 06e8 3a09 2ab4
    0x0000100: 00e5 b402 2713 06ea b605 a619 09b8 0441
    0x0000110: 9900 0db8 06ed 9a00 0704 a700 0403 b506
    0x0000120: f2bb 06f4 5919 09b7 06f7 3a0a 2ab4 00e5
    0x0000130: b601 843a 0b19 0bb4 06fa 190b b401 ca19
    0x0000140: 0bb4 06fa 6724 8d6b 6339 0c19 0bb4 06fd
    0x0000150: 190b b401 cd19 0bb4 06fd 6724 8d6b 6339
    0x0000160: 0e19 0bb4 0700 190b b401 d419 0bb4 0700
    0x0000170: 6724 8d6b 6339 1015 0599 0011 190a 180c
    0x0000180: 180e 1810 b807 04a7 0010 190a 180c 180e
    0x0000190: 1810 b907 0907 00b8 070c 9a00 0fb8 070f
    0x00001a0: 9a00 09b8 0712 9900 96b2 0715 9a00 902a
    0x00001b0: 0224 b707 182a b400 e5b4 0227 1307 1ab6
    0x00001c0: 05a6 1117 01b8 0400 b804 032a 2404 b704
    0x00001d0: 112a b400 e5b4 0169 862a b400 e5b4 016c
    0x00001e0: 866e 1301 af2a b400 cdb8 0416 1117 00b8
    0x00001f0: 0400 1505 9900 06b8 071d 1906 241b b607
    0x0000200: 2015 0599 0006 b807 2311 1701 b804 00b8
    0x0000210: 0403 2a24 04b7 0411 2ab4 00e5 b401 6986
    0x0000220: 2ab4 00e5 b401 6c86 6e13 01af 2ab4 00cd
    0x0000230: b804 1611 1700 b804 00a7 0006 b807 262a
    0x0000240: 0324 b707 1811 1d01 b807 2919 0bb4 01cd
    0x0000250: 190b b601 d18d 6314 072a 2ab4 00e5 b401
    0x0000260: a1b4 072e 12cb 6a8d 6398 9c00 112a 1906
    0x0000270: 241b 180c 180e 1810 b707 322a b400 e5b4
    0x0000280: 0227 1307 34b6 05a6 2a03 24b7 0718 2ab4
    0x0000290: 00e5 b600 f3b2 0739 b604 81b8 073e 2ab4
    0x00002a0: 00e5 b402 2713 0740 b605 a62a 190b 2419
    0x00002b0: 0a2a b400 e5b4 01c2 b607 43b7 0747 1505
    0x00002c0: 9900 2619 0619 0b24 8d19 0a2a 59b4 0749
    0x00002d0: 5a04 60b5 0749 2ab4 00e5 b401 c2b6 0743
    0x00002e0: b807 4da7 0023 1906 190b 248d 190a 2a59
    0x00002f0: b407 495a 0460 b507 492a b400 e5b4 01c2
    0x0000300: b607 43b6 0751 1b99 0008 1b05 a000 272a
    0x0000310: b400 e5b4 0227 1307 53b6 05a6 b207 57b6
    0x0000320: 075a 2ab4 00e5 b402 1a21 b607 5eb2 0757
    0x0000330: b607 612a b400 e5b4 0227 1307 63b6 05a6
    0x0000340: b207 66b6 075a 2ab4 00e5 b401 a1b4 0769
    0x0000350: 9900 241b 9e00 202a b400 e5b4 0227 1307
    0x0000360: 6bb6 05a6 b807 702a b400 e5b4 0227 1307
    0x0000370: 63b6 05a6 1117 00b8 0400 b804 49b8 0773
    0x0000380: 1505 9900 06b8 0776 1906 b207 7c24 8d1b
    0x0000390: 190b b607 8057 b806 a915 0599 0006 b807
    0x00003a0: 832a b400 e5b6 00f3 b207 39b6 0787 032a
    0x00003b0: b400 e5b4 01a1 b407 8a9e 0007 04a7 0004
    0x00003c0: 03b9 0790 0300 1906 b207 9324 8d1b 190b
    0x00003d0: b607 8057 2ab4 00e5 b600 f3b2 0739 b607
    0x00003e0: 87b9 0796 0100 2ab4 00e5 b600 f3b2 0739
    0x00003f0: b607 8703 03b9 0790 0300 1505 9900 06b8
    0x0000400: 0799 1906 b207 9c24 8d1b 190b b607 8057
    0x0000410: 2ab4 00e5 b600 f3b2 0739 b607 87b9 0796
    0x0000420: 0100 1505 9900 06b8 079f b207 66b6 0761
    0x0000430: 111d 00b8 0729 1102 0413 01eb b805 aa2a
    0x0000440: b402 e69a 0064 1117 00b8 0400 b804 67b8
    0x0000450: 0449 b807 a22a b400 e5b4 0227 1307 a4b6
    0x0000460: 05a6 b207 a7b6 0153 9900 14b2 07a7 04bd
    0x0000470: 0005 5903 03b8 05e1 53b8 038c 1906 190b
    0x0000480: 190a 24b6 07ab b207 a7b6 0153 9900 14b2
    0x0000490: 07a7 04bd 0005 5903 02b8 05e1 53b8 038c
    0x00004a0: b807 3e2a b604 6411 1700 b804 00b8 0467
    0x00004b0: 1508 9900 7a2a b400 e5b4 0242 c600 7019
    0x00004c0: 0bb2 031b b607 af9a 0065 190b c003 483a
    0x00004d0: 12b8 0773 2ab4 00e5 b402 2713 07b1 b605
    0x00004e0: a6b2 07b4 b601 5399 0032 b207 b408 bd00
    0x00004f0: 0559 0319 0653 5904 1912 5359 052a b400
    0x0000500: e5b4 0242 5359 0603 b805 e153 5907 24b8
    0x0000510: 0325 53b8 07b7 9a00 1319 0619 122a b400
    0x0000520: e5b4 0242 0324 b607 bbb8 06a9 2ab4 00e5
    0x0000530: b407 bfb6 07c4 9900 1cb8 07c7 3612 b807
    0x0000540: ca2a b400 e5b4 07bf 2421 b607 cd15 12b8
    0x0000550: 07d0 1906 b407 d4b9 07d9 0100 9a00 5c2a
    0x0000560: b400 e5b4 0227 1307 dbb6 05a6 b807 deb2
    0x0000570: 07e2 b207 e6b2 07e8 b207 ebb8 07ef 2ab4
    0x0000580: 00e5 b600 f3b2 0739 b607 8703 03b9 0790
    0x0000590: 0300 1906 b807 f5b8 07f5 b607 f919 0b24
    0x00005a0: b607 fd2a b400 e5b6 00f3 b207 39b6 0787
    0x00005b0: b907 9601 00b8 0726 1103 0211 0303 0403
    0x00005c0: b808 00b8 0726 2ab4 02e6 9a00 562a b604
    0x00005d0: 582a b400 e5b4 0227 1308 02b6 05a6 1505
    0x00005e0: 9900 06b8 0805 1907 190b 24b6 080b b807
    0x00005f0: 3e2a 0324 b707 182a b400 e5b4 0227 1308
    0x0000600: 0db6 05a6 1505 9900 06b8 0810 1907 190b
    0x0000610: 24b6 0813 1505 9900 06b8 0816 2ab6 0464
    0x0000620: 03b8 0819 b804 4199 0009 b808 1cb8 0819
    0x0000630: b806 c22a b400 e5b4 0227 1308 1eb6 05a6
    0x0000640: 1505 9900 06b8 0821 2a24 b608 2415 0599
    0x0000650: 0006 b808 2704 b808 1919 0619 0b24 b608
    0x0000660: 2a15 0599 000c 2a24 1bb8 082e b808 31b8
    0x0000670: 0726 b806 c2b2 07e2 b208 34b2 07e8 b207
    0x0000680: ebb8 07ef 1102 0413 01eb b805 aa2a 0324
    0x0000690: b707 18b8 07de 03b8 0819 2ab4 00e5 b600
    0x00006a0: f3b2 0739 b604 8111 1d01 b807 292a b400
    0x00006b0: e5b4 0227 1308 36b6 05a6 1b24 1909 2ab8
    0x00006c0: 083c 1505 9900 06b8 083f 1906 b208 4224
    0x00006d0: 8d1b 190b b607 8057 1505 9900 06b8 0845
    0x00006e0: b207 a7b6 0153 9900 5d2a b402 e69a 0056
    0x00006f0: b807 a22a b400 e5b4 0227 1307 a4b6 05a6
    0x0000700: b207 a704 bd00 0559 0304 b805 e153 b803
    0x0000710: 8c2a b400 e5b4 021a 190b 190a 24b6 07ab
    0x0000720: b207 e2b2 0834 b207 e8b2 07eb b807 efb2
    0x0000730: 07a7 04bd 0005 5903 02b8 05e1 53b8 038c
    0x0000740: b807 3e11 1d00 b807 2904 b808 19b8 06c2
    0x0000750: b807 26b8 07ca 190b b401 cd19 0bb6 01d1
    0x0000760: 8d63 1407 2a2a b400 e5b4 01a1 b407 2e12
    0x0000770: cb6a 8d63 979b 001e 2ab4 00e5 b402 2713
    0x0000780: 0847 b605 a62a 1906 241b 180c 180e 1810
    0x0000790: b707 32b2 084a b601 5399 0026 2ab4 00e5
    0x00007a0: b402 2713 084c b605 a6b2 084a 05bd 0005
    0x00007b0: 5903 1906 5359 0424 b803 2553 b803 8c2a
    0x00007c0: b400 e5b4 0227 1308 4eb6 05a6 2ab4 00ac
    0x00007d0: 9900 31b2 0715 9a00 2b15 0599 000c 2a24
    0x00007e0: 1bb8 0851 b808 5411 0100 b805 d915 0599
    0x00007f0: 000c 2a24 1bb8 0857 a700 092a 241b b708
    0x0000800: 5915 0599 0006 b808 5cb1               
  Stackmap Table:
    append_frame(@16,Integer)
    append_frame(@83,Object[#540],Object[#2055],Integer)
    same_frame(@102)
    same_frame(@121)
    same_frame(@149)
    full_frame(@195,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer},{Object[#336],Object[#2149],Object[#2149],Integer})
    full_frame(@196,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer},{Object[#336],Object[#2149],Object[#2149],Integer,Integer})
    same_frame(@207)
    same_locals_1_stack_item_frame(@232,Object[#1055])
    full_frame(@233,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer},{Object[#1055],Integer})
    same_frame(@236)
    full_frame(@285,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer,Object[#1775]},{Object[#1775]})
    full_frame(@286,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer,Object[#1775]},{Object[#1775],Integer})
    full_frame(@394,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer,Object[#1775],Object[#1780],Object[#455],Double,Double,Double},{})
    same_frame(@407)
    same_frame(@425)
    same_frame_extended(@506)
    same_frame(@521)
    same_frame(@572)
    same_frame(@575)
    same_frame(@635)
    same_frame_extended(@742)
    same_frame(@774)
    same_frame(@783)
    same_frame(@819)
    same_frame_extended(@884)
    same_frame(@904)
    same_frame(@929)
    full_frame(@960,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer,Object[#1775],Object[#1780],Object[#455],Double,Double,Double},{Object[#1932],Integer})
    full_frame(@961,{Object[#2],Integer,Float,Long,Integer,Object[#540],Object[#2055],Integer,Object[#1775],Object[#1780],Object[#455],Double,Double,Double},{Object[#1932],Integer,Integer})
    same_frame_extended(@1026)
    same_frame(@1066)
    same_frame_extended(@1148)
    same_frame(@1184)
    same_frame(@1191)
    append_frame(@1305,Object[#840])
    same_frame(@1321)
    chop_frame(@1324,1)
    same_frame(@1362)
    same_frame_extended(@1464)
    same_frame(@1510)
    same_frame(@1548)
    same_frame(@1564)
    same_frame(@1568)
    same_frame(@1584)
    same_frame(@1608)
    same_frame(@1621)
    same_frame(@1647)
    same_frame_extended(@1738)
    same_frame(@1760)
    same_frame_extended(@1859)
    same_frame_extended(@1939)
    same_frame(@1983)
    same_frame(@2023)
    same_frame(@2043)
    same_frame(@2049)
    same_frame(@2057)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:523)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:523)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 304613064 bytes (290 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                    | Source                                         | Signature                                |
	|:----- |:--------------- |:-------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2                     | minecraft.jar                                  | None                                     |
	| LCH   | mcp             | 9.42                       | minecraft.jar                                  | None                                     |
	| LCH   | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCH   | forge           | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCH   | cubicchunkscore | 1.12.2-0.0.1161.0-SNAPSHOT | minecraft.jar                                  | None                                     |
	| LCH   | hammercore      | 2.0.6.26                   | HammerLib-1.12.2-2.0.6.26.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | lux             | 12.4.18                    | ColoredLux-1.12.2-12.4.18.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | cubicchunks     | 1.12.2-0.0.1161.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1161.0-SNAPSHOT-all.jar | None                                     |
	| LCH   | musiclayer      | 12.3.21                    | MusicLayer-1.12.2-12.3.21.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | terraria        | 12.3.21                    | TerrariaCraft-1.12.2-12.3.21.jar               | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |

	Loaded coremods (and transformers): 
TerrariaCraftCoremod (TerrariaCraft-1.12.2-12.3.21.jar)
  tk.zeitheron.terraria.asm.TerrariaCraftASM
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1161.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
HCASM (HammerLib-1.12.2-2.0.6.26.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14757 Compatibility Profile Context 20.12.1 27.20.14501.28009' Renderer: 'AMD Radeon R7 350 Series'
	HammerCore Debug Information: 
		Dependent Mods:
			-Colored Lux (lux) @ 12.4.18
			-Music Layer (musiclayer) @ 12.3.21
			-Terraria Craft (terraria) @ 12.3.21

	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 350 Series GL version 4.6.14757 Compatibility Profile Context 20.12.1 27.20.14501.28009, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14757 Compatibility Profile Context 20.12.1 27.20.14501.28009
	OpenGlRenderer: AMD Radeon R7 350 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Zeitheron** [comment]
delete optifine.
