### ISSUE TITLE
Players disconnect with "Internal Server Error" when trying to connect to the server

### ISSUE THREAD

**Issue by Etrainquandt17** [TerrariaCraft/Issues#29]
Server Log:
27.01 18:49:14 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@73d436cd:
27.01 18:49:14 [Server] INFO java.lang.NullPointerException: null
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.world.api.WorldgenHelper.getBiome(WorldgenHelper.java:35) ~[WorldgenHelper.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:147) ~[TerrariaBiomeRegistry.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:86) ~[TerrariaBiomeRegistry.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:79) ~[TerrariaBiomeRegistry.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.common.data.player.PlayerDataTC.update_end(PlayerDataTC.java:328) ~[PlayerDataTC.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.common.data.DataLoaderTC.playerTick(DataLoaderTC.java:133) ~[DataLoaderTC.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_DataLoaderTC_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) [FMLCommonHandler.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) [aed.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [aed.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
27.01 18:49:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
27.01 18:49:14 [Server] Server thread/ERROR [FML]: Index: 1 Listeners:
27.01 18:49:14 [Server] Server thread/ERROR [FML]: 0: NORMAL
27.01 18:49:14 [Server] Server thread/ERROR [FML]: 1: ASM: class tk.zeitheron.terraria.common.data.DataLoaderTC playerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
27.01 18:49:14 [Server] Server thread/ERROR [FML]: 2: ASM: com.zeitheron.hammercore.specials.Zeitheron.ZeitheronGlobEvents@42f6328c playerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
27.01 18:49:14 [Server] Server thread/ERROR [FML]: 3: ASM: com.zeitheron.hammercore.world.WorldGenHelper@22a024bf chunkLoad(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
27.01 18:49:14 [Server] Server thread/ERROR [FML]: 4: ASM: tk.zeitheron.terraria.common.events.EventListenerPlayer@7b18819b playerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
27.01 18:49:14 [Server] Server thread/WARN [minecraft/NetworkSystem]: Failed to handle packet for /24.77.39.55:57978
27.01 18:49:14 [Server] INFO net.minecraft.util.ReportedException: Ticking player
27.01 18:49:14 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
27.01 18:49:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
27.01 18:49:14 [Server] INFO Caused by: java.lang.NullPointerException
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.world.api.WorldgenHelper.getBiome(WorldgenHelper.java:35) ~[WorldgenHelper.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:147) ~[TerrariaBiomeRegistry.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:86) ~[TerrariaBiomeRegistry.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.biome.api.TerrariaBiomeRegistry.forPosition(TerrariaBiomeRegistry.java:79) ~[TerrariaBiomeRegistry.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.common.data.player.PlayerDataTC.update_end(PlayerDataTC.java:328) ~[PlayerDataTC.class:?]
27.01 18:49:14 [Server] INFO at tk.zeitheron.terraria.common.data.DataLoaderTC.playerTick(DataLoaderTC.java:133) ~[DataLoaderTC.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_DataLoaderTC_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
27.01 18:49:14 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) ~[FMLCommonHandler.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) ~[aed.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[aed.class:?]
27.01 18:49:14 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
27.01 18:49:14 [Server] INFO ... 9 more

**Comment by Zeitheron** [comment]
Ensure you have `level-type=Terraria` in `server.properties`

But generally speaking, multiplayer isn't something that I could recommend running in general.
