### ISSUE TITLE
[BUG] Fallen Star Rarity

### ISSUE THREAD

**Issue by 3mdnu0fu0y** [TerrariaCraft/Issues#30]
**Describe the bug**
In normal Terraria I can get anywhere from 4 to 12 fallen stars when hunting for them at night.  However, after several hours of playing the mod and MANY nights (definitely more than 10) of standing still or running around I've only accumulated 5 fallen stars total.

**Expected behavior**
Fallen Stars to be FAR more common.

**Mod Versions**
![mods 1_28_2021 8_01_44 PM](https://user-images.githubusercontent.com/78142298/106122234-3106eb80-61a4-11eb-8bf2-d72992f9e5d7.png)

 **Hardware & Software info (Might be important in some cases)**
 - CPU: [Intel Core i7-9750H CPU @ 2.60GHz]
 - GPU: [NVIDIA GeForce RTX 2060 MOBILE 90W TGP]
 - RAM: [16 GBs @ 2667 MHz] (8 allocated to Minecraft)
 - Java: [Java 8 Update 281 (64-bit)]

**Additional context**
Add any other context about the problem here. For example, if your game crashes, attach a link to [Pastebin](pastebin.com) with a crash report pasted in there (full crash report, do not strip any part of it, it might be crucial for figuring the issue out!)

hi

**Comment by Zeitheron** [comment]
Hello, I was tinking about reworking how stars fall in general to prevent this rarity.
It became a problem when cubic chunks was added. Vertical cubes got unloaded causing stars to freeze in the sky.
We'll make it a separate event to make it cube-independent. Stay tuned for more information.
