### ISSUE TITLE
Enemies only spawn behind you

### ISSUE THREAD

**Issue by 3mdnu0fu0y** [TerrariaCraft/Issues#31]
Enemies never seem to spawn in front of the player.  I don't know if this is a bug or intended, but if it's intended I can only assume that it's to stop entities popping out of nowhere from breaking immersion.  Though that may be the case, I would say that the issue of always having to look behind you to find enemies is a far bigger issue.  One of Terraria's biggest draws for me is fun and fast paced combat that gives nice rewards.  If you're running around looking for foes to fight, then stopping and turning around seems pretty counterintuitive and ruins the fast paced actiony vibe that  Terraria is all about.  If it's choosing between the two, I absolutely choose enemies popping out of thin air to face you in battle, over every enemy just hiding behind you almost always escaping and reducing the amount of combat in the game significantly.  Whether or not this weird behavior is a bug or intentional, I hope that this report is helpful.

**Mod Versions**
![mods 1_28_2021 8_01_44 PM](https://user-images.githubusercontent.com/78142298/106123566-cce52700-61a5-11eb-8362-2982ba84f749.png)
 
 **Hardware & Software info**
 - CPU: [Intel Core i7-9750H CPU @ 2.60GHz]
 - GPU: [NVIDIA GeForce RTX 2060 MOBILE 90W TGP]
 - RAM: [16 GBs @ 2667 MHz] (8 allocated to Minecraft)
 - Java: [Java 8 Update 281 (64-bit)]

**Comment by Zeitheron** [comment]
We have reduced the view angle from 180  degrees to `FOV/2` or behind blocks. This way enemies will be more likely to spawn infront, but only if there is a wall between spawning place and player to prevent sudden enemies appearance partially.

Considering as fixed.
