### ISSUE TITLE
Minecraft Crash at start up!

### ISSUE THREAD

**Issue by GJungle1** [TerrariaCraft/Issues#34]
https://pastebin.com/HHhfziY9

**Comment by GJungle1** [comment]
Is there any reason why this is happening?

**Comment by Zeitheron** [comment]
I do not know. Seems like a random issue on a small percentage of machines. Also does not seem to be reproducable.

**Comment by DyXaska** [comment]
I have the same problem

**Comment by DyXaska** [comment]
I fixed it, it is worth once again making sure that Optifine is not installed.
