### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Astral2003** [TerrariaCraft/Issues#36]
https://pastebin.com/zB9HbBbg

Game crashes during mod loading. RAM cap not reached. Running recommended Forge version 12.2.2-14.23.5.2847

**Comment by Zeitheron** [comment]
Outdated version of CC?

**Comment by Astral2003** [comment]
That'd do it. Thanks, and sorry for being an idiot.

**Comment by Zeitheron** [comment]
Glad this solved the issue that easy!
