### ISSUE TITLE
No Hammer Lib Version Available for this Mod

### ISSUE THREAD

**Issue by Firecrazznss** [TerrariaCraft/Issues#38]
When you follow the link in the mod's description for hammer lib, it takes you to a page with no 1.12 version. This is a major problem for this mod, as this mod is 1.12, making this mod unusable since hammer lib is required for this mod. How am I supposed to play the mod if a required mod for it isn't compatible with the Minecraft version this mod uses?

**Comment by Zeitheron** [comment]
Not really an issue, just gotta be more careful next time
https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files
