### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Xman1130** [TerrariaCraft/Issues#39]
I cant download the version of 1.12 forge you want and i don't know why i need help with figuring that out but when I boot up the terraria craft launcher and load a world it just crashes saying terraria craft is the problem 
https://pastebin.com/W9ncwfe9

**Comment by Zeitheron** [comment]
upload the crash report to pastebin.com

**Comment by Zeitheron** [comment]
The issue is:
Running old TerrariaCraft (12.4.24) with ColoredLux (12.3.20)

Can happen vice-versa.

New Terraria Craft (12.5.25) must be run with the new ColoredLux (12.4.24);
Old Terraria Craft must be run with old ColoredLux
