### ISSUE TITLE
Consider Cubic Chunk Support

### ISSUE THREAD

**Issue by maxZ-2020** [TerrariaCraft/Issues#4]
Consider Supporting OpenCubicCunks for WorldGen. Minecraft World height is 256 Meters.
OpenCubicChunks World height is 64km. This way you can have the original Terraria vertical Biomes.

https://www.curseforge.com/minecraft/mc-mods/opencubicchunks

From what I understand it is about as easy to write a Worldgen  based on OpenCubicChunks as it is for default Minecraft.

**Comment by DeropManz** [comment]
I too would enjoy this.

**Comment by Zeitheron** [comment]
In new versions, that mod is required to run TerrariaCraft, we have done some compat work with CC's mod developer, and I am happy to replace my old nether system to a humongous world where floating clouds, caverns, hell and all things would be possible.
