### ISSUE TITLE
crashing from AI pathing

### ISSUE THREAD

**Issue by FlutterTree** [TerrariaCraft/Issues#40]
made a house it was night time and i started to dig into the floor of my house. removed lux thinking it was a lighting issue casuing the crashes but then crashed again. crash report talks about path finding relating to a "twiggy zombie". 

using AT launcher.
Terraria Craft 12.4.25
Terraria Craft Assets 12.4-0
MC Forge 14.23.5.2847

Third time it crashed
https://pastebin.com/TVTbhPrB

seccond time it crashed
https://pastebin.com/EY6D0gfM

first time it crashed
https://pastebin.com/2LWBHpiF

**Comment by JoSuperMaster** [comment]
Probably an issue from the hammer lib, i dont know how but i heard hammer lib also helps with custom entities because it helps the code of terraria craft soo probably you're having an old ver of hammer lib or something..?

**Comment by FlutterTree** [comment]
not in a server

**Comment by FlutterTree** [comment]
> wait, are you in a server? that might be the problem, because the mod doesnr support dedicated servers.

not in a server

> Probably an issue from the hammer lib, i dont know how but i heard hammer lib also helps with custom entities because it helps the code of terraria craft soo probably you're having an old ver of hammer lib or something..?

using the latest version of hammer for 1.12.2

**Comment by Zeitheron** [comment]
I couldn't ever replicate it, not got any more confirmations. This might be a bug in Forge. Might be some weird entity loading order issue.
Regardless, I don't think it's relevant anymore.
