### ISSUE TITLE
forge-1.12.2-14.23.5.2847-installer.jar failing to open, I had no idea where to post this...

### ISSUE THREAD

**Issue by Solypsist27** [TerrariaCraft/Issues#43]
When I try to open the specific forge version installer on my pc, nothing happens and a crash report appears in my Download folder. Since its the only forge version supported and I have no idea if there's any other way to install it, it appears I have no way of playing the mod at the moment. Is this a known forge issue?
I have Java Version 8 Update 301 installed, I reinstalled it after uninstalling it from the control panel to make sure the installation was done correctly
I'm running on windows 10 home (64bit) on a Huawei Matebook D15
Processor: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx 2.30 GHz
Ram: 8,00 Gb
The crash report that appears is this one:
[installer.log](https://github.com/TerrariaCraft/Issues/files/7346839/installer.log)
Let me know if more information is needed, or if this isn't the right place to post it, I decided to try anyway because I really want to play this mod and I couldn't find anything else online

**Comment by Zeitheron** [comment]
This is completely forge's fault, we can not do anything about it except suggesting to use our launcher (downloadable on our discord server) or using CurseForge app.
