### ISSUE TITLE
The game crash

### ISSUE THREAD

**Issue by wandou12581** [TerrariaCraft/Issues#5]
**To Reproduce**
1. play game
2. See error

![捕获](https://user-images.githubusercontent.com/65123447/81503401-fc9d8780-9315-11ea-82a3-4cfe951dcd7b.PNG)
[crash-2020-05-10_23.30.41-client.txt](https://github.com/TerrariaCraft/Issues/files/4605930/crash-2020-05-10_23.30.41-client.txt)

**Expected behavior**

**Screenshots**

**Mod Versions (please complete the following information):**
 - Minecraft Forge: [14.23.5.2847]
 - HammerLib (HammerCore) [2.0.6.17]
 - TerrariaCraft [12.1.5]
 - MusicLayer [18r]
 - (if installed) ColoredLux [ 12r]
 - Optifine Installed: yes (Only required for visual debugging)

**Additional context**

**Comment by Zeitheron** [comment]
From what I can see, your ISP doesn't let direct connection to github. You might need to use system-wide VPN while launching game to solve this. Pretty sure there is nothing our team can do here.
