### ISSUE TITLE
[BUG] Mining Issue

### ISSUE THREAD

**Issue by Luneskie** [TerrariaCraft/Issues#51]
**Describe the bug**
Having an issue with mining in general, I think when you're near a mob or any grass you'll double swing. Which in turn delays your mining all together.

**To Reproduce**
1. Stand next to any grown grass (not the grass block but grass grown on top), or mob for that matter.
2. Try mining a block.
3. You'll still mine but get a double swing with the audio and you may not chip at the block sometimes.

**Expected behavior**
Well pretty much just expect the mining to work properly really.

**Screenshots**
Umm, would have to be a video chief.

**Mod Versions (please complete the following information):**
 - Minecraft Forge: [e.g. 14.23.5.2855]
 - HammerLib (HammerCore) [e.g. 2.0.6.28]
 - TerrariaCraft [e.g. 12.4.25]
 - MusicLayer [e.g. 12.3.21]
 - OpenCubicChunks [e.g. 0.0.1184.0]
 - (if installed) ColoredLux [e.g. 12.6.29]
 - (if installed) Corsair McCUE [e.g. 12.4.8]
 - Optifine Installed: [yes/no] No optifine.
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Intel Core i5-9600K @ 3.70GHz
 - GPU: AMD Radeon R9 390 Series
 - RAM: 16GB @ 2667 MHz
 - Java: Java 8 Update 291 (64-bit)

**Additional context**
Just that the double audio gets annoying, same with the delayed mining. Who knows, I may be out of date.

**Comment by Zeitheron** [comment]
Fixed.
