### ISSUE TITLE
[BUG] server freeze upon entering specific caves

### ISSUE THREAD

**Issue by zombieseatflesh7** [TerrariaCraft/Issues#54]
**Describe the bug**
sometimes when i am traveling through a cave, the server will freeze completely and i will be unable to mine or pick up items. In addition, all entities freeze in place and the chat stops working. However, i can still walk around and place blocks. Trying to save and quit causes the game to freeze indefinitely and i have to force quit the game. This only happens when i enter specific areas, and it happens even if i restart the game.

**To Reproduce**
specific chunks in caves, when loaded, consistently cause server death. Turning down the render distance seems to help, until i get too close to whatever is causing the problem. I have no idea what is causing this.

**Expected behavior**
At the bare minimum, the game should at least crash and give me a crash log. haha.
The game should not freeze when i enter specific areas.

**Mod Versions (please complete the following information):**
I am using the latest version from the terrariacraft launcher.
Colored lux and optimization mods are enabled in the settings.
4GB of ram allocated.
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
 - GPU: NVIDIA GeForce GTX 1050 Ti
 - RAM: 12 GB 2133 MHz
 - Java: Java 8 Update 241 (64-bit)

**Additional context**
because i have to force quit the game, the log really doesnt contain any information about the crash.

**Comment by Frank-Einstein** [comment]
Try deactivating Lux in the options, it was crashing my game quite a lot. 
It didn't crash a single time after that, for a few hours...
