### ISSUE TITLE
Crash from the launcher

### ISSUE THREAD

**Issue by MysticFlaymes** [TerrariaCraft/Issues#55]
I tried to play it from the latest version and 12.4.25 but it keeps crashing
https://pastebin.com/Gtuyyr5b

**Comment by Uhhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
Excuse me, but how do you uninstall McCue?
<img width="565" alt="Screen Shot 2021-12-12 at 11 51 53 AM" src="https://user-images.githubusercontent.com/95949879/145699548-c565fc03-adfe-4780-8e71-e4c9316c09f3.png">
n
