### ISSUE TITLE
[BUG] Rain effect passing through roof placed glass

### ISSUE THREAD

**Issue by DraLUSAD** [TerrariaCraft/Issues#58]
Rain & slime rain visuals are phasing through glass
![Untitled](https://user-images.githubusercontent.com/57923958/139424955-1b56d060-2bc0-454b-b2dd-84c27480c3d4.png)
s

**Comment by Zeitheron** [comment]
This issue is fixed from my end (TerrariaCraft used to use getHeight instead of getPreciptationHeight), although the issue is still not going to be resolved, as it is also found in [CubicChunks#45](https://github.com/OpenCubicChunks/CubicChunks/issues/45)
