### ISSUE TITLE
[Suggestion] QoL Suggestions & Nit-picks

### ISSUE THREAD

**Issue by DraLUSAD** [TerrariaCraft/Issues#59]
**NPC Housing**
- [x] Craft-able NPC banners to be placed in valid housings, which forces NPCs to move in or around homes, this should give you a more flexible way when assigning NPC homes, when either they die, or need to be re-houses

**Ores to Bars**
- [x] I've noticed Iron/lead and Demonite/crimtane require 1 more ore to make bars, they should be 3 ores, instead of 4 ores (PC Variant)

**Fishing**
- [x] Without a way to moving water, tunnelling from the ocean to the desired biome is a nightmare, but plausible, however, I also believe the **Crate** potion effect needs to be balanced, sure I'm getting tones of Wooden Crates, but I feel the ratio for Iron, Biome and gold crates needs to be adjusted (Biome crates are slightly more common than gold, making their chance to appear more frequent between Iron and gold, it shouldn't take you 2hrs to acquire 1 biome crate)

**Golden & Biome chests**
- [x] Important loot for the chest loot table is different, but to be fair, taking hours to finding ONE gold chest, and only getting 2 dynamite and a gold coin is.... depressing, gold chest/biome chests/cabin chests should always grant 1 specific item, a low chance for a magic mirror (Ice mirror) and a mixture of random items.

**Empty corner block hit detection**
- [x] Building homes/tunnels and leaving those corners empty, mobs can feely attack you from said corners, even behind closed doors.

**Sand for hardened sand**
- [x] It needs hardened sand blocks, upon world gen these blocks needs to replace the bottom sand block where their is air, this prevents sand from collapsing early, example of this would be the ocean biome where a cave is big enough for sand to fall through, and causes the ocean to drain, resulting in massive lag spikes.

**Different armour, same stats**
- [x] Specially for jungle armour, having a mixture of Ancient Cobalt & Jungle do not give the Set bonus stat (where as the PC version does)

**Comment by Zeitheron** [comment]
I'll do a check list of things that need addressing...
* [x] NPC Housing
* [x] Ores -> Bars
* [x] Fishing
* [x] Chests tweaks
* [x] Sand for hardened sand
* [x] Different armour, same stats

**Comment by Zeitheron** [comment]
Progress so far:
- The bars will be merged into 12.6.2 as I didn't have time to check it according to wiki. (it was resolved)
- NPC Housing is now done through separate tab, so it's kind of a solved issue, just with a different approach
- Hardened sand has been a part of 12.5.32, but I didn't check it off.
- Chests are somewhat improved (they generate more frequently in 12.6 builds)
- Set bonus for ancient cobalt & jungle armor is now resolved. (will be merged into 12.6.2)

Other parts:
- Will have to inspect fishing a bit, but from what I remember it seemed pretty normal; You can move water with buckets now, so first part of it is resolved.

**Comment by DraLUSAD** [comment]
Oh my, this was a 2~3 year post, though its pretty good to see the mod still being worked on though, I may take another deep dive on it once another major release is open for the public :)
