### ISSUE TITLE
Incompatibility with Music Layer - 12.2.20 (latest)

### ISSUE THREAD

**Issue by SylisMC** [TerrariaCraft/Issues#6]
Hey, i just thought you should know that TC fails to launch with the lastest version of Music Layer saying it needs version 18 or higher (the last version)

It may be because they changed the way they display versions
https://www.curseforge.com/minecraft/mc-mods/music-layer/files
(using 18 for now untill its updated)

**Comment by Zeitheron** [comment]
This issue has been resolved in the upcoming public build.
We had to change versioning to make it easier to understand, and version system changes are never good with mods that depend on said mods.
