### ISSUE TITLE
game freeze

### ISSUE THREAD

**Issue by SavageCatClaw** [TerrariaCraft/Issues#60]
so, i have a problem, i was going underground, i found a house with one of those purple things in it (idk what its called), i opened the chest, took everything in the chest, exited the chest and then opened my inventory, and i couldn't move any items, and i also couldn't attack, break blocks, interact with blocks (such as opening a door), i couldn't place blocks either, so i tried to quit the game and it completely froze and i had to alt f4

**Comment by Frank-Einstein** [comment]
I think I had pretty much the same problem. It was crashing every 5 minutes or so... I deactivated the Lux option for the lights and it didn't crash a single time after that, played for a few hours without any problem. I also removed the McCue plugin.
You can try that.
