### ISSUE TITLE
It freezes

### ISSUE THREAD

**Issue by NiteMarauder** [TerrariaCraft/Issues#66]
Every time I try to create a world the game freezes at 0%, what can I do to fix it?

**Comment by Zeitheron** [comment]
Please open minecraft folder and find the following file: .minecraft/logs/latest.log
Open it with text editor and copy all of it into pastebin.com, then create a paste and send a link here for further investigation.

**Comment by Zeitheron** [comment]
That is not full log, but only system details.  Please provide the entire log.

**Comment by NiteMarauder** [comment]
Sorry, is this the whole thing? https://pastebin.com/eB69La7K

**Comment by Zeitheron** [comment]
Yep! Seems like the game is out of memory, try allocating 6-8 GBs of RAM!

**Comment by NiteMarauder** [comment]
Okay

**Comment by NiteMarauder** [comment]
Odd, my computer says my RAM usage isn't all that high but my computer lags when it's open

**Comment by NiteMarauder** [comment]
Oh never mind it takes 70% percent of the RAM, so that is precisely the problem

**Comment by NiteMarauder** [comment]
Thanks for the help

**Comment by Zeitheron** [comment]
no problem!

**Comment by Uhhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
I tried to allocate more ram in curseforge but it still doesn't work. I couldn't find the file either (using a mac)

**Comment by Uhhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
and before i go in the game it says the mod hammercore always fails to load for some reason

**Comment by Uhhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
@Zeitheron is there a way to solve this?

**Comment by Uhhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
plus, I can't get the link when the hammer-core-failed-to-load page comes up

**Comment by Uhhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
<img width="1062" alt="Screen Shot 2021-12-11 at 10 48 53 PM" src="https://user-images.githubusercontent.com/95949879/145680873-e6582468-4348-46e0-b46e-bbdf920d3ca2.png">

**Comment by Uhhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
<img width="1091" alt="Screen Shot 2021-12-11 at 10 52 24 PM" src="https://user-images.githubusercontent.com/95949879/145680971-bedfbc16-f1ea-446c-913e-39def6ba0457.png">
this is what happens when I try to re-download the mod on curseforge
