### ISSUE TITLE
Minecraft won't open after Forge Loading screen[BUG] 

### ISSUE THREAD

**Issue by TheMalePerson** [TerrariaCraft/Issues#73]
I tried downloading the mod, with all its mod requirements. But the Game won't open. It loads the Forge page but then it freezes with the Minecraft dirt texture. (Also I have a Mac)

![image](https://user-images.githubusercontent.com/97476853/148833516-c6cd680e-5f26-47ce-a982-ae9670013d59.png)
<img width="851" alt="Screen Shot 2022-01-10 at 3 30 00 PM" src="https://user-images.githubusercontent.com/97476853/148832660-98dd46ed-9c69-4e4e-b069-a3555e2f459c.png">

Then I tried downloading the installer. and the game doesn't open either.

What should I do?

Mod Versions:
- Minecraft forge: 1.12.2-forge1.12.2-14.23.5.2847
- ColoredLux-1.12.2-12.6.30
- CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all
- HammerLib-1.12.2-2.0.6.31
- MusicLayer-1.12.2-12.3.21
- TerrariaCraft-1.12.2-12.5.30

Hardware:
- MacBook Pro 2015 15inch
- CPU: 2.5 GHz Quad-Core Intel Core i7
- RAM: 16 GB 1600 MHz DDR3
- GPU: Intel Iris Pro 1536 MB
- Java: JAVA 8 (64-bit)
 
Crash Report:
This is before I have to force quit it minecraft.
https://pastebin.pl/view/d9c0eff7

And after it only says Process crashed with exit code 143.

**Comment by Zeitheron** [comment]
Please provide full logs, the "crash report" you have posted does not contain any useful information, sadly.

**Comment by TheMalePerson** [comment]
https://pastebin.pl/view/e846b52a
Here you go

**Comment by TheMalePerson** [comment]
Im not familiar with sending log reports so if it's not that, please explain.

This is the latest log report i could find. I tried the crash reports but since it didn't actually crash, there was no report i could find from today.

**Comment by Zeitheron** [comment]
The issue seems to be with memory allocation failing on mac. Try to give it a bit more RAM and see if that helps.

**Comment by TheMalePerson** [comment]
I tried putting 12gig, but the same thing happened :(.

https://pastebin.pl/view/b90fd95e

**Comment by TheMalePerson** [comment]
Maybe I'm not doing it correctly?

![image](https://user-images.githubusercontent.com/97476853/148837897-f8f0e94c-2e14-468c-a1c5-0e5a551b66f0.png)

**Comment by ProjectInfinity2** [comment]
I have the exact same divice and its also not working

**Comment by Zeitheron** [comment]
I can't seem to make it work for mac, sorry.
