### ISSUE TITLE
[BUG] [resolved but i cant change the status]

### ISSUE THREAD

**Issue by ImJC1C** [TerrariaCraft/Issues#75]
**Describe the bug**
Bug makes it so after going into a new world with an AMD GPU at least, half of the sky becomes black and sometimes jittery, it makes the game visually unplayable

**To Reproduce**
1. Launch the game
2. Open a world or create a new one
3. Let it generate
4. Move

**Expected behavior**
Half of the sky is black as noticed on the featured screenshot

**Screenshots**
![2022-01-18_20 24 52](https://user-images.githubusercontent.com/97984491/150005222-5b68220d-1435-4264-a620-e8b8d4498247.png)

 - Minecraft Forge: 14.23.5.2847(also tested on 14.23.5.2860, the same results)
 - HammerLib (HammerCore) 2.0.6.31
 - TerrariaCraft 12.5.30
 - MusicLayer 12.3.21
 - OpenCubicChunks 0.0.1208.0
 - ColoredLux installed 12.6.30
 - Corsair McCUE installed 12.4.8
 - Optifine Installed: no

**Comment by Zeitheron** [comment]
This issue might be a driver-level problem, I can not replicate it, and this is the first time it has ever been reported.

**Comment by ImJC1C** [comment]
im updating my drivers, ill respond if that fixed it

**Comment by Zeitheron** [comment]
Would also be helpful if you listed your hardware

**Comment by ImJC1C** [comment]
CPU: AMD Ryzen 5 3600
RAM: 16GB
GPU: AMD Radeon RX 5600 XT
OS: Windows 10 Pro 64bit
Motherboard: MAG B550M Mortar

**Comment by Zeitheron** [comment]
Huh, seems like a new build to me. I'm confused.

**Comment by ImJC1C** [comment]
could see why

**Comment by ImJC1C** [comment]
i just updated my drivers, and the same happens

**Comment by Zeitheron** [comment]
Do you by chance have any other mods? They may alter the rendering pipeline and cause this issue to happen.

**Comment by ImJC1C** [comment]
these are the only ones i have, im now removing them one by one to check which one may be the problem, if that changes anything, i used the curseforge modpack

**Comment by ImJC1C** [comment]
i finally figured it out, the sinner was...... Overwolf
