### ISSUE TITLE
[BUG] can't see other player on Lan game

### ISSUE THREAD

**Issue by phambatu2002** [TerrariaCraft/Issues#79]
**Screenshots**
![image](https://user-images.githubusercontent.com/100915405/156724584-797f94cd-ffeb-4c91-8fc5-6cd1b47aeda3.png)

**Mod Versions (please complete the following information):**
 - Minecraft Forge: [e.g. 14.23.5.2847]
 - HammerLib (HammerCore) [e.g. 2.0.6.19]
 - TerrariaCraft [e.g. 12.2.17]
 - MusicLayer [e.g. 12.2.20]
 - OpenCubicChunks [e.g. 0.0.1055.0]
 - (if installed) ColoredLux [e.g. 12.3.17]
 - (if installed) Corsair McCUE [e.g. 12.2.5]
 - Optifine Installed: yes

**Comment by XxsjrapsxX** [comment]
last time i check isnt optifine not supported by opencubicchunks?

**Comment by Zeitheron** [comment]
Technically, multiplayer isn't compatible as of now.
I'm closing this until multiplayer will be officially supported and thoroughly tested.
If it will happen afterwards - feel free to re-open this issue, or create a new one.
