### ISSUE TITLE
Server Bug

### ISSUE THREAD

**Issue by clarius72470** [TerrariaCraft/Issues#8]
Hello I wanted to do a serv with my friends with the mod but I did not succeed because there was a problem with the mod can you help me please: 

[18:27:29] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
--
1193 | net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Terraria Craft (terraria)
1194 |  
1195 | Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureAtlasSprite
1196 | at tk.zeitheron.terraria.init.BlocksTC.<clinit>(BlocksTC.java:98) ~[BlocksTC.class:?]
1197 | at tk.zeitheron.terraria.biome.BiomeForest.initBiome(BiomeForest.java:31) ~[BiomeForest.class:?]
1198 | at tk.zeitheron.terraria.biome.api.TerrariaBiome.<init>(TerrariaBiome.java:31) ~[TerrariaBiome.class:?]
1199 | at tk.zeitheron.terraria.biome.BiomeForest.<init>(BiomeForest.java:25) ~[BiomeForest.class:?]
1200 | at tk.zeitheron.terraria.init.BiomesTC.<clinit>(BiomesTC.java:14) ~[BiomesTC.class:?]
1201 | at tk.zeitheron.terraria.api.world.WorldBiomeType$1.<init>(WorldBiomeType.java:41) ~[WorldBiomeType$1.class:?]
1202 | at tk.zeitheron.terraria.api.world.WorldBiomeType.<clinit>(WorldBiomeType.java:38) ~[WorldBiomeType.class:?]
1203 | at tk.zeitheron.terraria.init.ItemsTC.<clinit>(ItemsTC.java:219) ~[ItemsTC.class:?]
1204 | at tk.zeitheron.terraria.TerrariaCraft.preInit(TerrariaCraft.java:188) ~[TerrariaCraft.class:?]
1205 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1206 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1207 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1208 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1209 | at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge.jar:?]
1210 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1211 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1212 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1213 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1214 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1215 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1216 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1217 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1218 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1219 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1220 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1221 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge.jar:?]
1222 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge.jar:?]
1223 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1224 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1225 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1226 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1227 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1228 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1229 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1230 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1231 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1232 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1233 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1234 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
1235 | at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) ~[Loader.class:?]
1236 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
1237 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
1238 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
1239 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
1240 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
1241 | Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureAtlasSprite
1242 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
1243 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
1244 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
1245 | at tk.zeitheron.terraria.init.BlocksTC.<clinit>(BlocksTC.java:98) ~[BlocksTC.class:?]
1246 | at tk.zeitheron.terraria.biome.BiomeForest.initBiome(BiomeForest.java:31) ~[BiomeForest.class:?]
1247 | at tk.zeitheron.terraria.biome.api.TerrariaBiome.<init>(TerrariaBiome.java:31) ~[TerrariaBiome.class:?]
1248 | at tk.zeitheron.terraria.biome.BiomeForest.<init>(BiomeForest.java:25) ~[BiomeForest.class:?]
1249 | at tk.zeitheron.terraria.init.BiomesTC.<clinit>(BiomesTC.java:14) ~[BiomesTC.class:?]
1250 | at tk.zeitheron.terraria.api.world.WorldBiomeType$1.<init>(WorldBiomeType.java:41) ~[WorldBiomeType$1.class:?]
1251 | at tk.zeitheron.terraria.api.world.WorldBiomeType.<clinit>(WorldBiomeType.java:38) ~[WorldBiomeType.class:?]
1252 | at tk.zeitheron.terraria.init.ItemsTC.<clinit>(ItemsTC.java:219) ~[ItemsTC.class:?]
1253 | at tk.zeitheron.terraria.TerrariaCraft.preInit(TerrariaCraft.java:188) ~[TerrariaCraft.class:?]
1254 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1255 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1256 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1257 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1258 | at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge.jar:?]
1259 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1260 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1261 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1262 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1263 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1264 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1265 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1266 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1267 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1268 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1269 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1270 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge.jar:?]
1271 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge.jar:?]
1272 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1273 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1274 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1275 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1276 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1277 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1278 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1279 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1280 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1281 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1282 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1283 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
1284 | at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) ~[Loader.class:?]
1285 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
1286 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
1287 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
1288 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
1289 | at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
1290 | Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3a022576 from coremod FMLCorePlugin
1291 | at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge.jar:?]
1292 | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
1293 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
1294 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
1295 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
1296 | at tk.zeitheron.terraria.init.BlocksTC.<clinit>(BlocksTC.java:98) ~[BlocksTC.class:?]
1297 | at tk.zeitheron.terraria.biome.BiomeForest.initBiome(BiomeForest.java:31) ~[BiomeForest.class:?]
1298 | at tk.zeitheron.terraria.biome.api.TerrariaBiome.<init>(TerrariaBiome.java:31) ~[TerrariaBiome.class:?]
1299 | at tk.zeitheron.terraria.biome.BiomeForest.<init>(BiomeForest.java:25) ~[BiomeForest.class:?]
1300 | at tk.zeitheron.terraria.init.BiomesTC.<clinit>(BiomesTC.java:14) ~[BiomesTC.class:?]
1301 | at tk.zeitheron.terraria.api.world.WorldBiomeType$1.<init>(WorldBiomeType.java:41) ~[WorldBiomeType$1.class:?]
1302 | at tk.zeitheron.terraria.api.world.WorldBiomeType.<clinit>(WorldBiomeType.java:38) ~[WorldBiomeType.class:?]
1303 | at tk.zeitheron.terraria.init.ItemsTC.<clinit>(ItemsTC.java:219) ~[ItemsTC.class:?]
1304 | at tk.zeitheron.terraria.TerrariaCraft.preInit(TerrariaCraft.java:188) ~[TerrariaCraft.class:?]
1305 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1306 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1307 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1308 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1309 | at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge.jar:?]
1310 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1311 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1312 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1313 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1314 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1315 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1316 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1317 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1318 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1319 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1320 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1321 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge.jar:?]
1322 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge.jar:?]
1323 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1324 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1325 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1326 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1327 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1328 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1329 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1330 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1331 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1332 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1333 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1334 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
1335 | at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) ~[Loader.class:?]
1336 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
1337 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
1338 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
1339 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
1340 | at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
1341 | Caused by: java.lang.RuntimeException: Attempted to load class cdq for invalid side SERVER
1342 | at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge.jar:?]
1343 | at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge.jar:?]
1344 | at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
1345 | at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
1346 | at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
1347 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
1348 | at tk.zeitheron.terraria.init.BlocksTC.<clinit>(BlocksTC.java:98) ~[BlocksTC.class:?]
1349 | at tk.zeitheron.terraria.biome.BiomeForest.initBiome(BiomeForest.java:31) ~[BiomeForest.class:?]
1350 | at tk.zeitheron.terraria.biome.api.TerrariaBiome.<init>(TerrariaBiome.java:31) ~[TerrariaBiome.class:?]
1351 | at tk.zeitheron.terraria.biome.BiomeForest.<init>(BiomeForest.java:25) ~[BiomeForest.class:?]
1352 | at tk.zeitheron.terraria.init.BiomesTC.<clinit>(BiomesTC.java:14) ~[BiomesTC.class:?]
1353 | at tk.zeitheron.terraria.api.world.WorldBiomeType$1.<init>(WorldBiomeType.java:41) ~[WorldBiomeType$1.class:?]
1354 | at tk.zeitheron.terraria.api.world.WorldBiomeType.<clinit>(WorldBiomeType.java:38) ~[WorldBiomeType.class:?]
1355 | at tk.zeitheron.terraria.init.ItemsTC.<clinit>(ItemsTC.java:219) ~[ItemsTC.class:?]
1356 | at tk.zeitheron.terraria.TerrariaCraft.preInit(TerrariaCraft.java:188) ~[TerrariaCraft.class:?]
1357 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1358 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1359 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1360 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1361 | at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge.jar:?]
1362 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1363 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1364 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1365 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1366 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1367 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1368 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1369 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1370 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1371 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1372 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1373 | at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge.jar:?]
1374 | at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge.jar:?]
1375 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
1376 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
1377 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
1378 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
1379 | at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
1380 | at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
1381 | at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
1382 | at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
1383 | at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
1384 | at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
1385 | at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
1386 | at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
1387 | at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) ~[Loader.class:?]
1388 | at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
1389 | at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
1390 | at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
1391 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
1392 | at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
1393 | [18:27:29] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /server/./crash-reports/crash-2020-06-29_18.27.29-server.txt
 
![Capture d’écran (26)](https://user-images.githubusercontent.com/67599592/86033596-79590200-ba39-11ea-8598-8a72f6e49664.png)

**Comment by Zeitheron** [comment]
Further info will be in #11
