### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by P3r3tZ** [TerrariaCraft/Issues#82]
At first launch I had no textures. I saw the notification on the screen about it it, downloaded resourses and dragged them to .minecraft folder(I'm using curse forge app). Launched via curse forge and had infinite loading. I attached screenshot of the moment when loading stops and loading it forever. Maybe I've done smth wrong with resourses idk.
 I have 32gb ram
msi rtx 2080ti
intel core i7 10700k
edited: I've entered the game rn, but stil dont have resources
![image](https://user-images.githubusercontent.com/101329498/157698216-1d14561e-5f64-4894-b5eb-1e913af5a9b8.png)

**Comment by Zeitheron** [comment]
You have to enable the resource pack.

**Comment by Zeitheron** [comment]
Please ensure that you have put it in the correct folder and that you downloaded the resourcepack and not something else.

**Comment by P3r3tZ** [comment]
![image](https://user-images.githubusercontent.com/101329498/157701696-a15db7fc-5bab-4a6b-9c7d-73a5c2b2375c.png)
![image](https://user-images.githubusercontent.com/101329498/157701870-2460646d-b280-47f7-b6d2-c4157f3228dc.png)

**Comment by Zeitheron** [comment]
You downloaded repository, not resource pack. Please download resourcepack instead.

**Comment by P3r3tZ** [comment]
Where can I download it? The game says I need download it from here. I've downloaded it from here
![image](https://user-images.githubusercontent.com/101329498/157703050-2e6666dd-e713-4030-8720-90b002df1f6b.png)

**Comment by Zeitheron** [comment]
Yes, that is the correct link.

**Comment by Zeitheron** [comment]
But you have to download resource pack, not  the repository.
