### ISSUE TITLE
[BUG] Crash on Virtual Machine

### ISSUE THREAD

**Issue by REALbwGHOST** [TerrariaCraft/Issues#86]
While launching the game, it crashes. I am using a virtual machine

 - Minecraft Forge: 14.23.5.2860
 - HammerLib (HammerCore) 2.0.6.32
 - TerrariaCraft 12.5.32
 - MusicLayer 12.3.21
 - OpenCubicChunks 0.0.1208.0
 - (if installed) ColoredLux 12.6.30
 - (if installed) Corsair McCUE 12.4.8
 - Optifine Installed: no
 
 Hardware & Software info
 - CPU: 6x AMD Ryzen 5 5600X 6-Core Processor
 - GPU: NVIDIA 3070
 - RAM: 32GB
 - Java: Latest

I am using a virtual machine, and have tried all installation options for TerrariaCraft (curseforge, forge, launcher). The installation works fine on my PC. Other modpacks work fine on the VM.

https://pastebin.com/y18b9uPA

**Comment by Zeitheron** [comment]
Uninstall McCUE mod.

**Comment by REALbwGHOST** [comment]
Thanks!
