### ISSUE TITLE
[BUG] world loading

### ISSUE THREAD

**Issue by bobjr365** [TerrariaCraft/Issues#89]
When opening Minecraft through the curseForge app it crashes stating that Hammer Core as the potential cause 
<img width="1026" alt="Screen Shot 2022-07-24 at 6 20 29 pm" src="https://user-images.githubusercontent.com/109899603/180646471-7c24c84d-d2ac-461c-9efa-2c36091a77f2.png">
Clicking get link results in it saying it has failed 
then when clicking Back to title screen and trying to open a world it just stays a 0% 
<img width="1024" alt="Screen Shot 2022-07-24 at 6 22 29 pm" src="https://user-images.githubusercontent.com/109899603/180646474-8580ffd9-d8c8-4df1-b27f-d3d8e1677292.png">

McCUE removed 
Crash report 
[crash-2022-07-24_18.20.17-client.txt](https://github.com/TerrariaCraft/Issues/files/9175813/crash-2022-07-24_18.20.17-client.txt)

**Comment by Zeitheron** [comment]
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
