### ISSUE TITLE
NPCs not moving into house I built

### ISSUE THREAD

**Issue by Bubalo1234** [TerrariaCraft/Issues#95]
**WARNING!**
You must fill out the following information in order to receive any help.
Leaving things "as-is" does not provide us with any useful information.
This warning may be deleted.

**Describe the bug**

**To Reproduce**
1. Make a house
2. have an npc move into it
3. destroy that house
4. build a new house
5. wait until the next morning

**Expected behavior**
I thought that the NPCs would move into the other house I built for them. Also I had like 5 NPCs moved into the house I had? So I built them all houses but they refuse to move out. Then I destroyed my two houses hoping they would move in to the one I built.

**Screenshots**
My destroyed two houses:
<img width="1792" alt="destroyed houses" src="https://user-images.githubusercontent.com/80659275/199097069-5061fa72-c6dd-43a8-ad66-ea7eaabc99e6.png">

The inside of one of my new house:
<img width="1792" alt="house" src="https://user-images.githubusercontent.com/80659275/199097208-06432330-b869-4dcb-a897-1377682d4cef.png">

**Mod Versions (please complete the following information):**
 - Minecraft Forge: 14.23.5.2859
 - HammerLib (HammerCore): 2.0.6.32
 - TerrariaCraft: 12.5.32
 - MusicLayer: 12.2.21
 - OpenCubicChunks 0.0.1208.0
 - (if installed) ColoredLux: no
 - (if installed) Corsair McCUE: no
 - Optifine Installed: no
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: 2.3 GHz 8-Core Intel Core i9
 - GPU: Intel UHD Graphics 630 1536 MB
 - RAM: 16 GB 2667 MHz DDR4
 - Java: 8 Update 311

**Additional context**
I have MacBook Pro

**Comment by FoxbitDreamtail** [comment]
I think they are ignoring non-Windows issues....

**Comment by Zeitheron** [comment]
You might need to wait a bit longer for NPCs to arrive.
In the current public build the NPCs have a condition to move in that is checked periodically, and you have to be inside of a house to let them move in.
This is somewhat patched in current early access builds and is planned to rollout with next major public build. Stay tuned.
