### ISSUE TITLE
[BUG] Can't place Doors

### ISSUE THREAD

**Issue by SyndiShanX** [TerrariaCraft/Issues#96]
**Description**
I cannot place any doors for some reason

**Reproduction**
1. Craft a Door
2. Try to Place Said Door

**Expected behavior**
The Door goes from my hand into the Worldspace

**Mod Versions (Default Modpack)**
 - Minecraft Forge: 14.23.5.2860
 - BetterFps-1.4.8
 - ColoredLux: 12.6.30
 - CubicChunks: 0.0.1208.0
 - FoamFix: 0.10.14
 - HammerLib: 2.0.6.32
 - McCue: 12.4.8
 - MusicLayer: 12.3.21
 - TerrariaCraft: 12.5.32
 - TerrariaCraftRecipeViewer: 5.2.7
 - VanillaFix: 1.0.10-150
 - Optifine Installed: No
 
 **Hardware & Software info**
 - CPU: AMD Ryzen 5 5600G
 - GPU: AMD Radeon Graphics (Integrated into CPU)
 - RAM: 16GB @ 3600MHz
 - Java: 8.0.3320.9 (Default CurseForge)

**Comment by Zeitheron** [comment]
You probably forgot that it needs ro have ceiling beforehand.
